### ISSUE TITLE
TakingHTML2CanvasFullPageScreenshot doesn´t work for me

### ISSUE THREAD

**Issue by carolcruzc** [AutomateThePlanet/AutomateThePlanet-Learning-Series#5]
` string response = (string)js.ExecuteScript
                            ("return (typeof canvasImgContentDecoded === 'undefined' || canvasImgContentDecoded === null)");`

ERROR:
Additional information: 
Can not convert an object of type 'System.Boolean' to type 'System.String'.

**Comment by angelovstanton** [comment]
This is really strange since we use similar code in our product Bellatrix- http://bellatrix.solutions
and It works like a charm. Maybe depends on the web-page where you try to create the screenshot. Is it possible to send me the URL so that I can debug?

**Comment by Zhang-chang** [comment]
I try to capture the screenshot using html2canvas.
I copy the full source code from https://atp-dev.plam.ch/full-page-screenshots-webdriver-html2canvas/ and paste it my workspace.
But I get timeout error in calling for js.ExecuteScript().
I don't know why the error occurs.
I may my code and page url if requesting more detail information.
I appreciate your help.

**Comment by angelovstanton** [comment]
Sorry for my late answer for some reason I didn't have any notifications. You can download the full source code of our open-source framework BELLATRIX- https://bellatrix.solutions/ there we have a fully working version.
