### ISSUE TITLE
Issues with running AppiumTests

### ISSUE THREAD

**Issue by kkarakk** [AutomateThePlanet/AutomateThePlanet-Learning-Series#7]
i downloaded your appium sample for c# android and i'm getting these errors. googling doesn't reveal a quick solution. i think it is due to me upgrading the project to the latest version of all nuget packages. Although you haven't mentioned anything about that on your [article   ](https://www.automatetheplanet.com/getting-started-appium-android-csharp/)

> 'DesiredCapabilities.DesiredCapabilities()' is obsolete: 'Use of DesiredCapabilities has been deprecated in favor of browser-specific Options classes'	GettingStartedAppiumAndroidWindows	D:\VSProjects\Appium-Series\Appium-Series\GettingStartedAppiumAndroidWindowsCSharp\AppiumTests.cs

on 

```
var desiredCaps = new DesiredCapabilities();
            desiredCaps.SetCapability(MobileCapabilityType.DeviceName, "Android_Accelerated_x86_Oreo");
            desiredCaps.SetCapability(AndroidMobileCapabilityType.AppPackage, "io.appium.android.apis");
            desiredCaps.SetCapability(MobileCapabilityType.PlatformName, "Android");
            desiredCaps.SetCapability(MobileCapabilityType.PlatformVersion, "7.1");
            desiredCaps.SetCapability(AndroidMobileCapabilityType.AppActivity, ".ApiDemos");
            desiredCaps.SetCapability(MobileCapabilityType.App, testAppPath);
```

>Argument 1: cannot convert from 'OpenQA.Selenium.Appium.Service.AppiumLocalService' to 'OpenQA.Selenium.Remote.ICommandExecutor'	GettingStartedAppiumAndroidWindows	D:\VSProjects\Appium-Series\Appium-Series\GettingStartedAppiumAndroidWindowsCSharp\AppiumTests.cs

and

> Error	CS1503	Argument 2: cannot convert from 'OpenQA.Selenium.Remote.DesiredCapabilities' to 'OpenQA.Selenium.DriverOptions'	GettingStartedAppiumAndroidWindows	D:\VSProjects\Appium-Series\Appium-Series\GettingStartedAppiumAndroidWindowsCSharp\AppiumTests.cs	

on

` _driver = new AndroidDriver<AndroidElement>(_appiumLocalService, desiredCaps);`

There are multiple issues like this, should i just use the bundled package versions? is there no support on newer versions of appium?

**Comment by angelovstanton** [comment]
Sorry for my late answer. I didn't receive any notifications about the issue; not answering wasn't intentional. I have updated the article while ago and the examples too.
