### ISSUE TITLE
Issue with GettingStartedAppiumIOSMacOS

### ISSUE THREAD

**Issue by hisinh** [AutomateThePlanet/AutomateThePlanet-Learning-Series#9]
I am getting following error :
Class Initialization method GettingStartedAppiumIOSMacOS.AppiumTests.ClassInitialize threw exception. OpenQA.Selenium.WebDriverException: OpenQA.Selenium.WebDriverException: A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://0.0.0.0:4723/wd/hub/session. The status of the exception was UnknownError, and the message was: IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address.
Parameter name: hostName IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address.
Parameter name: hostName ---> System.Net.WebException: IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address.
Parameter name: hostName IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address.
Parameter name: hostName ---> System.Net.Http.HttpRequestException: IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address.
Parameter name: hostName ---> System.ArgumentException: IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address.
Parameter name: hostName.

**Comment by angelovstanton** [comment]
I would suggest submitting the issue to the Appium GitHub repository. And sorry for applying so late I haven't received a notification.
